# Generated by Django 5.2.4 on 2025-07-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_publish_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='title',
            field=models.CharField(default='image', max_length=250),
        ),
    ]
