# Generated by Django 5.2.4 on 2025-07-28 03:29

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postimage_title'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Culture', 'Culture'), ('Business', 'Business'), ('Lifestyle', 'Lifestyle'), ('Technology', 'Technology')], default='cul'),
        ),
    ]
