# Generated by Django 5.2.4 on 2025-07-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_managers_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='meta_description',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='no description'),
        ),
    ]
