# Generated by Django 5.2.4 on 2025-08-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_usercontact_user_folloeing'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='folloeing',
            new_name='following',
        ),
        migrations.AddField(
            model_name='post',
            name='total_like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-total_like_count'], name='blog_post_total_l_69e6b8_idx'),
        ),
    ]
