# Generated by Django 5.2.4 on 2025-08-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_folloeing_user_following_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercontact',
            options={'ordering': ['-create']},
        ),
        migrations.AddIndex(
            model_name='usercontact',
            index=models.Index(fields=['-create'], name='blog_userco_create_b83600_idx'),
        ),
    ]
